<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
  <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
  <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print">

  <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  <title>Write, write, write give your wings on code!</title>
</head>

<body>
  <header>
    <div class="inner">
      <h1><a href="http://theredfoxfire.github.io/">Hasan Setiawan</a></h1>
      <h2>Write, write, write give your wings on code!</h2>
      <a href="https://github.com/theredfoxfire" class="button"><small>Follow me on</small> GitHub</a>
    </div>
  </header>

  <div id="content-wrapper">
    <div class="inner clearfix">
      <section id="main-content">
        <h2>Javascript Promises - <code>reject</code> vs. <code>throw</code></h2>
        <p>
          There is no advantage of using one vs the other, but, there is a specific case where throw won't work. However, those cases can be fixed.
          Any time you are inside of a promise callback, you can use throw. However, if you're in any other asynchronous callback, you must use reject.
          For example:
          </p>
        <p>
          <blockquote>
            <pre>
              <code>
new Promise(function() {
  setTimeout(function() {
    throw 'or nah';
    // return Promise.reject('or nah'); also won't work
  }, 1000);
}).catch(function(e) {
  console.log(e); // doesn't happen
});
              </code>
            </pre>
          </blockquote>
        </p>
        <p>
          Won't trigger the catch, instead you're left with an unresolved promise and an uncaught exception.
          That is a case where you would want to instead use reject. However, you could fix this by promisifying the timeout:
        </p>
        <p>
          <blockquote>
            <pre>
              <code>
function timeout(duration) { // Thanks joews
  return new Promise(function(resolve) {
    setTimeout(resolve, duration);
  });
}

timeout(1000).then(function() {
  throw 'worky!';
  // return Promise.reject('worky'); also works
}).catch(function(e) {
  console.log(e); // 'worky!'
});
              </code>
            </pre>
          </blockquote>
        </p>
        <p>
          Worth mentioning that the places inside a non-promisified async callback that you can't use <code>throw error</code>,
          you also can't use return <code>Promise.reject(err)</code> which is what the OP was asking us to compare.
          This is basically why you should not put async callbacks inside of promises.
          Promisify everything that's async and then you don't have these restrictions.
        </p>
      </section>

      <aside id="sidebar">


        <p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.<br><br><hr/><a action="action" onclick="window.history.go(-1); return false;" href="#">Back</a></p>
        <h3>

        </h3>
      </aside>
    </div>
  </div>


</body>

</html>
